# \u65E5\u5FD7\u7EA7\u522B
logging:
  level:
    com.zhang: debug
  #\u6570\u636E\u5E93\u8FDE\u63A5\u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://47.98.37.85:3306/genealogy?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 2358mo
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 50
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  type-aliases-package: com.zhang.genealogy.model
  mapper-locations: classpath:mapper/*.xml
